apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::040179484449:role/eks-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-25T03:14:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2158"
  uid: 5923239a-5ddf-4209-93cf-03d545c466c1
data:
  mapUsers: |
    - userarn: arn:aws:iam::040179484449:user/workshop  
      username: admin
      groups:
        - system:masters
