apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::040179484449:role/eks-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-23T23:35:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1524"
  uid: 06b46a4b-bd2b-49f7-9e43-0f378bc07a46
data:
  mapUsers: |
    - userarn: arn:aws:iam::040179484449:user/workshop  
      username: admin
      groups:
        - system:masters
