apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::040179484449:role/eks-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-25T06:21:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1426"
  uid: c60b3f4f-d77d-4671-b4d9-4c65129e5be2
data:
  mapUsers: |
    - userarn: arn:aws:iam::040179484449:user/workshop  
      username: admin
      groups:
        - system:masters
