# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.rtbassoc-024cb38ce64e85194:
resource "aws_route_table_association" "rtbassoc-024cb38ce64e84754" {
  route_table_id = aws_route_table.rtb-0c9df3106b9e1aye2.id
  subnet_id      = aws_subnet.subnet-public.id
}

output "rtb-public" {
  value = aws_route_table.rtb-0c9df3106b9e1aye2.id
}